# -*- coding: utf-8 -*-
"""Gandhari.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EVCpsTPfu2G0lnHJE_3atHXUXkuDGQj8

# Gandhari Unicode を(本当の)Uniocdeに変換する

Unicodeの私用領域を駆使してサンスクリット語などの表記に必要な文字を表示するためのフォント「Gandhari Unicode」が使われている DOCX ファイルを変換します。

変換後のファイルは、結合文字が表示できるフォントで改めて保存してください。

## Google Drive のマウント

このノートブックは Google Drive 内の指定された DOCX ファイルを変換します。
Google Drive をマウントするには、以下のチェックを入れてコードを実行してください。
"""

# @title マウント実行
mount = False # @param {type:"boolean"}

from google.colab import drive

if mount == "Yes":
    drive.mount('/content/drive')
    print("マウントしました")

"""## 変換するファイルの指定

Google Drive 内の DOCX ファイルのパスまたは DOCX が置いてあるフォルダのパスを入力してください。

例：

- `sanskrit/veda/rigveda/rv1-1.docx`
- `sanskrit/veda/atharvaveda/`
"""

# @title ファイル or フォルダ指定
dir_path = "" # @param {type:"string"}

from pathlib import Path

path = "drive/MyDrive" / Path(dir_path)

if path.exists():
    if path.is_file():
        if path.suffix == "docx":
            print("docxファイルが指定されました")
            data_dir = path.parent
            docx_files = [path]
        else:
            print("指定されたファイルはdocxファイルではありません")
    elif path.is_dir():
        docx_files = list(path.glob("*.docx"))
        if len(docx_files) == 0:
            print("指定されたフォルダにdocxファイルが見つかりません")
        else:
            print("指定されたフォルダに以下のdocxファイルが見つかりました。")
            data_dir = path
            for file in docx_files:
                print(file.name)
else:
    print("パスが存在しません")

"""## 変換準備

以下のコードを実行して変換準備を行います。
https://github.com/Yuzki/SktTool/tree/master/utils のコードを利用しています。
"""

# @title
# 変換スクリプト
# def convert_unicode(text):
#     # ここに変換ロジックを実装
#     return text

data = [
    ("e800", "J̌"),
    ("e802", "J́"),
    ("e803", "j́"),
    ("e804", "J̄"),
    ("e805", "j̄"),
    ("e806", "L̥"),
    ("e807", "l̥"),
    ("e808", "M̄"),
    ("e809", "m̄"),
    ("e810", "M̥"),
    ("e811", "m̥"),
    ("e812", "N̄"),
    ("e813", "n̄"),
    ("e814", "N̥"),
    ("e815", "n̥"),
    ("e816", "Ś̄"),
    ("e817", "ś̄"),
    ("e818", "Ṣ̄"),
    ("e819", "ṣ̄"),
    ("e820", "S̄"),
    ("e821", "s̄"),
    ("e822", "S̱"),
    ("e823", "s̱"),
    ("e824", "Ṭ́"),
    ("e825", "ṭ́"),
    ("e826", "V́"),
    ("e827", "v́"),
    ("e828", "C̄"),
    ("e829", "c̄"),
    ("e82a", "D́"),
    ("e82b", "d́"),
    ("e82c", "Ḍ́"),
    ("e82d", "ḍ́"),
    ("e82e", "Ǵ̄"),
    ("e82f", "ǵ̄"),
    ("e830", "H́"),
    ("e831", "h́"),
    ("e834", "R̥"),
    ("e835", "r̥"),
    ("e836", "V̄"),
    ("e837", "v̄"),
    ("e838", "V̆"),
    ("e839", "v̆"),
    ("e83a", "?"),
    ("e83b", "H̄"),
    ("e83c", "h̄"),
    ("e842", "A͚"),
    ("e843", "a͚"),
    ("e844", "Ā̆"),
    ("e845", "ā̆"),
    ("e846", "Ā̃"),
    ("e847", "ā̃"),
    ("e848", "Ā̀"),
    ("e849", "ā̀"),
    ("e84a", "Ā́"),
    ("e84b", "ā́"),
    ("e84c", "Ī̆"),
    ("e84d", "ī̆"),
    ("e84e", "Ī̃"),
    ("e84f", "ī̃"),
    ("e850", "Ī̀"),
    ("e851", "ī̀"),
    ("e852", "Ī́"),
    ("e853", "ī́"),
    ("e854", "U͚"),
    ("e855", "u͚"),
    ("e856", "Ū̆"),
    ("e857", "ū̆"),
    ("e858", "Ū̃"),
    ("e859", "ū̃"),
    ("e85a", "Ū̀"),
    ("e85b", "ū̀"),
    ("e85c", "Ū́"),
    ("e85d", "ū́"),
    ("e860", "R̥̀"),
    ("e861", "r̥̀"),
    ("e862", "Ŕ̥"),
    ("e863", "ŕ̥"),
    ("e864", "R̥̄́"),
    ("e865", "r̥̄́"),
    ("e866", "L̃"),
    ("e867", "l̃"),
    ("e868", "L̐"),
    ("e869", "l̐"),
    ("e86a", "M̐"),
    ("e86b", "m̐"),
    ("e86c", "T́"),
    ("e86d", "t́"),
    ("e86e", "Ś̱"),
    ("e86f", "ś̱"),
    ("e870", "P̄"),
    ("e871", "p̄"),
    ("e872", "?"),
    ("e873", "Ã́"),
    ("e874", "ã́"),
    ("e876", "a̯"),
    ("e877", "ắ"),
    ("e878", "ẵ"),
    ("e879", "ấ"),
    ("e87a", "ä́"),
    ("e87b", "ä̃"),
    ("e87c", "ä̃́"),
    ("e87e", "ǟ́"),
    ("e87f", "ǟ̃"),
    ("e880", "ā̃́"),
    ("e881", "å̃"),
    ("e882", "å̄"),
    ("e883", "i̯"),
    ("e884", "ĭ́"),
    ("e885", "ĩ́"),
    ("e886", "u̯"),
    ("e887", "ŭ́"),
    ("e888", "ŭ̃"),
    ("e889", "ü̃"),
    ("e88a", "ǖ́"),
    ("e88b", "ṹ"),
    ("e88c", "ů̄"),
    ("e88d", "r̬"),
    ("e88e", "e̯"),
    ("e88f", "ĕ́"),
    ("e890", "ē̆"),
    ("e891", "ë́"),
    ("e892", "ë̆"),
    ("e893", "ẽ́"),
    ("e894", "ḗ"),
    ("e895", "ē̃"),
    ("e896", "ē̃́"),
    ("e897", "ə́"),
    ("e898", "ə̃"),
    ("e899", "ə̃́"),
    ("e89a", "ə̄"),
    ("e89b", "ə̄́"),
    ("e89c", "ə̄̃"),
    ("e89d", "ɛ́"),
    ("e89e", "ɛ̃"),
    ("e89f", "ɛ̄"),
    ("e8a0", "ɛ̄́"),
    ("e8a1", "ɛ̄̃"),
    ("e8a2", "o̯"),
    ("e8a3", "ŏ́"),
    ("e8a4", "ỗ"),
    ("e8a5", "ṍ"),
    ("e8a6", "ö́"),
    ("e8a7", "ö̆"),
    ("e8a8", "ȫ"),
    ("e8a9", "ȫ́"),
    ("e8aa", "ṓ"),
    ("e8ab", "ō̆"),
    ("e8ac", "ō̃"),
    ("e8ad", "ō̃́"),
    ("e8ae", "ọ̈"),
    ("e8af", "ọ̆"),
    ("e8b0", "ọ̄"),
    ("e8b1", "ọ̄́"),
    ("e8b2", "ọ̄̃"),
    ("e8b3", "ɔ̃"),
    ("e8b4", "ɔ̄"),
    ("e8b5", "ɔ̄́"),
    ("e8b6", "ɔ̄̃"),
    ("e8b7", "c̣"),
    ("e8b8", "j̈"),
    ("e8b9", "j̣"),
    ("e8ba", "ʌ́"),
    ("e8bb", "ʌ̃"),
    ("e8bc", "ʋ́"),
    ("e8bd", "x̌"),
    ("e8bf", "ọ"),
    ("e8c1", "?"),
    ("e8c5", "H̱"),
    ("e8c6", "R̥̄"),
    ("e8c7", "r̥̄"),
    ("e8c8", "L̥̄"),
    ("e8c9", "l̥̄"),
]

import csv

def convert_gandhari_to_unicode(sentence: str):
    unicode_mapping = {}
    for row in data:
        unicode_hex, converted_string = row
        unicode_mapping["0x" + unicode_hex] = converted_string

    sentence_unicode = ""
    for c in sentence:
        hex_char = hex(ord(c))
        try:
            sentence_unicode += unicode_mapping[hex_char]
        except:
            sentence_unicode += c

    return(sentence_unicode)

"""## 変換処理

変換されたファイルは、もとのファイル名末尾に `_converted` が付与された名前で保存されます。

変換を実行するには、以下の `conv` にチェックを入れてコードを実行してください。
"""

# @title 変換実行
conv = False # @param {type:"boolean"}

if conv:
    !pip install python-docx

    from docx import Document

    for file_name in docx_files:
        doc = Document(file_name)
        for paragraph in doc.paragraphs:
            for run in paragraph.runs:
                original = run.text
                converted = convert_gandhari_to_unicode(original)
                run.text = converted

        output_path = data_dir / Path(file_name.stem + "_converted.docx")
        doc.save(output_path)